### ISSUE TITLE
Still maintaining?

### ISSUE THREAD

**Issue by benjaminoakes** [benjaminoakes/delayed-plugins-airbrake#8]
> Currently maintained by [@ndbroadbent](https://github.com/ndbroadbent). Many thanks!

Hi @ndbroadbent!

Are you still interested in being a maintainer or would you like to be removed from the README, etc?

Take care,

Ben

P.S. [DocSpring](https://docspring.com/) seems really cool.  Good work!

**Comment by ndbroadbent** [comment]
Hi @benjaminoakes, sorry I haven't looked at this for a long time and no longer use Airbrake, so probably a good to remove me from the README. Thanks!

**Comment by benjaminoakes** [comment]
Will do!  Thank you for your contributions.
